export const themes = {
  default: {
    '--menu-background-color': 'white',
    '--menu-text-color': '#333',
    '--menu-font-family': '"Quicksand", sans-serif',
    '--menu-section-background-color': '#f8f9fa',
    '--menu-heading-color': '#007bff',
    '--menu-heading-font-family': '"Dancing Script", cursive',
    '--menu-item-name-color': '#333',
    '--menu-item-description-color': '#666',
  },
  dark: {
    '--menu-background-color': '#222',
    '--menu-text-color': '#f0f0f0',
    '--menu-font-family': '"Roboto", sans-serif',
    '--menu-section-background-color': '#333',
    '--menu-heading-color': '#4da6ff',
    '--menu-heading-font-family': '"Playfair Display", serif',
    '--menu-item-name-color': '#f0f0f0',
    '--menu-item-description-color': '#ccc',
  },
  elegant: {
    '--menu-background-color': '#f5e6d3',
    '--menu-text-color': '#4a4a4a',
    '--menu-font-family': '"Merriweather", serif',
    '--menu-section-background-color': '#fff',
    '--menu-heading-color': '#8b4513',
    '--menu-heading-font-family': '"Cormorant Garamond", serif',
    '--menu-item-name-color': '#4a4a4a',
    '--menu-item-description-color': '#6c6c6c',
  },
  modern: {
    '--menu-background-color': '#f0f4f8',
    '--menu-text-color': '#2d3748',
    '--menu-font-family': '"Montserrat", sans-serif',
    '--menu-section-background-color': '#ffffff',
    '--menu-heading-color': '#4a5568',
    '--menu-heading-font-family': '"Poppins", sans-serif',
    '--menu-item-name-color': '#2d3748',
    '--menu-item-description-color': '#718096',
  },
  circular: {
    '--menu-background-color': '#f0f0f0',
    '--menu-text-color': '#333',
    '--menu-font-family': '"Quicksand", sans-serif',
    '--menu-section-background-color': '#fff',
    '--menu-heading-color': '#ff6b6b',
    '--menu-heading-font-family': '"Pacifico", cursive',
    '--menu-item-name-color': '#333',
    '--menu-item-description-color': '#666',
    '--menu-layout': 'circular',
  },
  diagonal: {
    '--menu-background-color': '#222',
    '--menu-text-color': '#fff',
    '--menu-font-family': '"Oswald", sans-serif',
    '--menu-section-background-color': '#333',
    '--menu-heading-color': '#ffd700',
    '--menu-heading-font-family': '"Bebas Neue", cursive',
    '--menu-item-name-color': '#fff',
    '--menu-item-description-color': '#ccc',
    '--menu-layout': 'diagonal',
  },
  stacked: {
    '--menu-background-color': '#e6f3ff',
    '--menu-text-color': '#2c3e50',
    '--menu-font-family': '"Lato", sans-serif',
    '--menu-section-background-color': '#fff',
    '--menu-heading-color': '#3498db',
    '--menu-heading-font-family': '"Righteous", cursive',
    '--menu-item-name-color': '#2c3e50',
    '--menu-item-description-color': '#7f8c8d',
    '--menu-layout': 'stacked',
  },
};

export type ThemeName = keyof typeof themes;
